___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
arr2=np.ones(10)
arr2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [6]:
arr3=np.ones(10)
arr3[:]=5
arr3

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [8]:
arr4=np.arange(10,53,1)
arr4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52])

#### Create an array of all the even integers from 10 to 50

In [9]:
arr4=np.arange(10,54,2)
arr4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
arr5=np.arange(0,9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [12]:
arr6=np.eye(3)
arr6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [16]:
arr7=np.random.rand(1)
arr7

array([0.12614319])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [18]:
arr8=np.random.randn(4,4) 
arr8

array([[-1.15324526, -0.55529752, -1.53501982, -0.1987021 ],
       [-0.79206172, -0.64965791, -0.5484746 , -0.13611204],
       [ 1.2675804 ,  0.25541512, -0.55960678, -0.62447405],
       [ 1.97852724,  0.70907689,  0.75234103, -0.71857054]])

#### Create the following matrix:

In [20]:
arr9=np.linspace(0,5,5)
arr9

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [21]:
arr10=np.linspace(0,1,20)
arr10

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [24]:
arr10_0=[np.arange(12,16,1), np.arange(17,21,1), np.arange(22,26,1)]
arr10=np.array(arr10_0)
arr10

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [27]:
arr10[1,3]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [3]:
import numpy as np
arr13=[2,7,12]
arr14=np.array(arr13).reshape(3,1)
arr14
mat = np.arange(1,26).reshape(5,5)
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
#same technique as the above

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [49]:
#same technique as the above

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [29]:
mat = np.arange(1,26).reshape(5,5)
np.sum(mat) #mat.sum() 

325

#### Get the standard deviation of the values in mat

In [37]:

np.std(mat) #mat.std()
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all the columns in mat

In [4]:
np.sum(mat[0,0:1]) #pandas will solve the issue

1

# Great Job!